### ISSUE TITLE
bug(callFirestore): where clause doesn't work with 'delete' action

### ISSUE THREAD

**Issue by ebeloded** [prescottprue/cypress-firebase#307]
The following call removed all documents in the 'workspaces' collection

```ts
cy.callFirestore('delete', 'workspaces', {
    where: ['__TEST_DOC', '==', true],
})
```

**Expected behavior/code**

Expected only workspaces with `__TEST_DOC` equal `true`  to be deleted.

**Possible Solution**

A possible solution is to use `get` action, for which the `where` clause works, and delete each doc by referencing its id

**Comment by A13k2** [comment]
Can confirm that it works by chaining the commands:
```ts
cy.callFirestore('get', 'tests', {
      where: ['foo', '==', 'bar'],
    }).then((test) =>
      cy.wrap(
        test?.map((t: { id: string }) =>
          cy.callFirestore('delete', `tests/${t.id}`),
        ),
      ),
    );
```

I think this should at least be mentioned in the documentation. If you don't use the emulator, some people might accidentally delete whole collections.... 🔥

**Comment by prescottprue** [comment]
Thanks for reaching out - I'm looking into this today, agreed that it isn't expected

**Comment by prescottprue** [comment]
Addressed in [v1.8.1 release](https://github.com/prescottprue/cypress-firebase/releases/tag/v1.8.1). Thanks for reporting!

**Comment by farahanjum** [comment]
The issue still exists in v2.0.0. 

```js
cy.callFirestore('delete', 'testCollection', {
    where: ['testKey', '==', 'testVal'],
})
```

deletes the entire `testCollection`
